#!/usr/bin/env zsh

. "${DOTFILES}/helpers/brew.sh"
. "${DOTFILES}/helpers/cmd.sh"
. "${DOTFILES}/helpers/io.sh"

############
# homebrew #
############

() {
  if dir_exists "$(brew_prefix)"; then
    # Set up brew in the current shell environment.
    eval "$("$(brew_prefix)/bin/brew" shellenv)"
  fi
}

#############
# oh-my-zsh #
#############

() {
  if file_exists "${ZSH}/oh-my-zsh.sh"; then
    plugins=(httpie zsh-lazyload)
    source "$ZSH/oh-my-zsh.sh"
  fi
}

############
# lazyload #
#############

() {
  local NVM_BIN="$(brew_prefix nvm)/nvm.sh"
  local JENV_BIN="$(brew_prefix jenv)/bin/jenv"

  if file_exists "${NVM_BIN}"; then
    lazyload nvm node npm npx -- "source ${NVM_BIN}"
  fi

  if file_exists "${JENV_BIN}"; then
    lazyload jenv java mvn -- "eval \"\$(${JENV_BIN} init -)\""
  fi
}
# vim: set syntax=zsh: